#!/usr/bin/env node
/**
 * Reads VERSION.txt and injects the version into the TypeScript build:
 * - Writes ts-src/version.generated.ts for runtime use.
 * - Updates package.json version so npm pack / install show the same version.
 * Single source of truth: VERSION.txt (repo root).
 */

import { readFileSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const versionPath = join(root, "VERSION.txt");
const version = readFileSync(versionPath, "utf8").trim();

const generatedTs = `/** Generated by scripts/inject-version.mjs from VERSION.txt - do not edit */\nexport const VERSION = "${version}";\n`;
writeFileSync(join(root, "ts-src", "version.generated.ts"), generatedTs);

const pkgPath = join(root, "package.json");
const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
pkg.version = version;
writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");

console.log("Injected version:", version);
